// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/discover": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/favorites": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/discover" | "/profile" | "/favorites" | "/signup" | "/login";
  };
  "./layouts/sidebar.tsx": {
    id: "layouts/sidebar";
    page: "/" | "/discover" | "/profile" | "/favorites";
  };
  "./routes/Home.tsx": {
    id: "routes/Home";
    page: "/";
  };
  "./routes/Discover.tsx": {
    id: "routes/Discover";
    page: "/discover";
  };
  "./routes/Profile.tsx": {
    id: "routes/Profile";
    page: "/profile";
  };
  "./routes/Favorites.tsx": {
    id: "routes/Favorites";
    page: "/favorites";
  };
  "./routes/Signup.tsx": {
    id: "routes/Signup";
    page: "/signup";
  };
  "./routes/Login.tsx": {
    id: "routes/Login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "layouts/sidebar": typeof import("./src/app/./layouts/sidebar.tsx");
  "routes/Home": typeof import("./src/app/./routes/Home.tsx");
  "routes/Discover": typeof import("./src/app/./routes/Discover.tsx");
  "routes/Profile": typeof import("./src/app/./routes/Profile.tsx");
  "routes/Favorites": typeof import("./src/app/./routes/Favorites.tsx");
  "routes/Signup": typeof import("./src/app/./routes/Signup.tsx");
  "routes/Login": typeof import("./src/app/./routes/Login.tsx");
};